# Generated by Django 5.1.1 on 2025-10-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_ingredientrecipe_ingredient_is_already_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(default=0, max_length=30, verbose_name='Короткая ссылка на рецепт'),
            preserve_default=False,
        ),
    ]
