# Generated by Django 5.1.1 on 2025-10-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_fguser_first_name_alter_fguser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fguser',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Логин'),
        ),
    ]
